# Generated by Django 5.2.3 on 2025-07-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food & Dining", "Food & Dining"),
                    ("Transportation", "Transportation"),
                    ("Housing", "Housing"),
                    ("Utilities", "Utilities"),
                    ("Entertainment", "Entertainment"),
                    ("Shopping", "Shopping"),
                    ("Miscellaneous", "Miscellaneous"),
                ],
                max_length=100,
            ),
        ),
    ]
